"""
Automated Telemetry Monitor & GitHub Issue Reporter (src/telemetry_monitor.py)
Evaluates connector performance and data freshness metrics logged in data/connector_telemetry.json.
If connector failures, degraded success rates (< 95%), or stale data payloads (> 24h) are detected,
or on scheduled telemetry audit runs, automatically files an appropriately labeled issue on GitHub.
"""

import os
import sys
import json
import logging
import subprocess
from datetime import datetime
from src.connector_telemetry import get_telemetry_summary, generate_telemetry_report

logger = logging.getLogger(__name__)


def check_existing_open_telemetry_issue(repo: str = "KoshiirRa/midgley") -> bool:
    """Checks if an open telemetry issue already exists on GitHub to prevent duplicate issues."""
    try:
        cmd = ["gh", "issue", "list", "--repo", repo, "--search", "label:telemetry state:open", "--json", "number,title"]
        res = subprocess.run(cmd, capture_output=True, text=True, check=True)
        issues = json.loads(res.stdout) if res.stdout else []
        return len(issues) > 0
    except Exception as e:
        logger.debug(f"Notice checking existing GitHub telemetry issues: {e}")
        return False


def create_github_telemetry_issue(
    title: str,
    body: str,
    repo: str = "KoshiirRa/midgley",
    labels: str = "telemetry,data-ingestion,health-check,automated-audit",
    milestone: str = 'Regular Model v1.5 "Houdry"'
) -> dict:
    """Creates a new GitHub issue with specified labels and milestone."""
    if os.environ.get("TESTING") == "1":
        logger.info("TESTING=1: Suppressed GitHub issue creation.")
        return {"status": "TEST_SUPPRESSED"}

    try:
        cmd = [
            "gh", "issue", "create",
            "--repo", repo,
            "--title", title,
            "--body", body,
            "--label", labels
        ]
        if milestone:
            cmd.extend(["--milestone", milestone])

        res = subprocess.run(cmd, capture_output=True, text=True, check=True)
        issue_url = res.stdout.strip()
        logger.info(f"Successfully created GitHub telemetry issue: {issue_url}")
        return {"status": "SUCCESS", "issue_url": issue_url}
    except Exception as e:
        logger.error(f"Failed to create GitHub telemetry issue: {e}")
        return {"status": "ERROR", "message": str(e)}


def audit_telemetry_and_report_issues(days: int = 3, force_report: bool = False) -> dict:
    """
    Evaluates connector performance over the last N days.
    If health issues are found (or force_report=True), files a GitHub issue.
    """
    logger.info(f"Running automated connector telemetry audit ({days}-day window)...")
    summary = get_telemetry_summary(days=days)

    total_calls = summary.get("total_calls", 0)
    overall_success = summary.get("success_rate_pct", 100.0)
    stale_count = summary.get("stale_payload_count", 0)
    avg_latency = summary.get("avg_latency_ms", 0.0)
    connectors = summary.get("connectors", {})

    degraded_connectors = []
    for c_name, meta in connectors.items():
        c_success = meta.get("success_rate_pct", 100.0)
        c_stale = meta.get("stale_calls", 0)
        c_age = meta.get("avg_data_age_hours", 0.0)
        if c_success < 90.0 or c_stale > 3 or c_age > 24.0:
            degraded_connectors.append({
                "name": c_name,
                "success_rate": c_success,
                "stale_calls": c_stale,
                "avg_data_age": c_age
            })

    is_degraded = len(degraded_connectors) > 0 or overall_success < 95.0 or stale_count > 5

    if not is_degraded and not force_report:
        logger.info("Telemetry audit passed cleanly: all connectors healthy with zero degradation.")
        return {
            "status": "HEALTHY",
            "is_degraded": False,
            "summary": summary,
            "issue_created": False
        }

    # Avoid duplicate open issue spamming
    if check_existing_open_telemetry_issue():
        logger.info("An open telemetry issue already exists on GitHub. Skipping duplicate creation.")
        return {
            "status": "OPEN_ISSUE_EXISTS",
            "is_degraded": is_degraded,
            "summary": summary,
            "issue_created": False
        }

    # Format GitHub Issue Title & Body
    status_str = "DEGRADED" if is_degraded else "ROUTINE REPORT"
    title = f"[Telemetry Audit] {status_str}: Data Connector Health & Freshness Audit ({datetime.now().strftime('%Y-%m-%d')})"

    report_md = generate_telemetry_report(days=days)
    body_lines = [
        f"## Automated Connector Telemetry Audit ({status_str})",
        "",
        "This issue was automatically generated by the **Dev Server Telemetry Monitor Job** (`src/telemetry_monitor.py`).",
        "",
        "### Audit Findings",
        f"- **Health Status:** `{status_str}`",
        f"- **Evaluation Window:** `{days} days`",
        f"- **Overall Success Rate:** `{overall_success}%`",
        f"- **Stale Payloads Flagged (>24h):** `{stale_count}`",
        f"- **Degraded Connectors Identified:** `{len(degraded_connectors)}`",
        ""
    ]

    if degraded_connectors:
        body_lines.append("### Degraded Connectors Requiring Attention")
        for dc in degraded_connectors:
            body_lines.append(
                f"- **`{dc['name']}`**: Success Rate `{dc['success_rate']}%` | Stale Calls `{dc['stale_calls']}` | Avg Data Age `{dc['avg_data_age']}h`"
            )
        body_lines.append("")

    body_lines.append(report_md)
    body_lines.extend([
        "",
        "---",
        "**Action Items:**",
        "- Inspect `data/connector_telemetry.json` for detailed call logs.",
        "- Verify upstream REST endpoints or web scrapers for degraded connectors.",
        "- Close this issue once connectors return to >95% healthy operation."
    ])

    issue_body = "\n".join(body_lines)
    result = create_github_telemetry_issue(title=title, body=issue_body)
    return {
        "status": "ISSUE_FILED" if result.get("status") == "SUCCESS" else "ERROR",
        "is_degraded": is_degraded,
        "summary": summary,
        "issue_created": result.get("status") == "SUCCESS",
        "issue_result": result
    }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    force = "--force" in sys.argv
    res = audit_telemetry_and_report_issues(days=3, force_report=force)
    print(json.dumps(res, indent=2))
